# MySQL address, user and password
# user must have replication privilege in MySQL.
mysql_addr = "127.0.0.1:3306"
mysql_user = "root"
mysql_pass = "yaoyichen52"
mysql_charset = "utf8"

# Path to store data, like master.info, if not set or empty,
# we must use this to support breakpoint resume syncing.
# TODO: support other storage, like etcd.
data_dir = "./var"

# Inner Http status address
stat_addr = "127.0.0.1:12800"
stat_path = "/metrics"

# pseudo server id like a slave
server_id = 1001

# mysql or mariadb
flavor = "mysql"

# mysqldump execution path
# if not set or empty, ignore mysqldump.
mysqldump = "mysqldump"

# if we have no privilege to use mysqldump with --master-data,
# we must skip it.
#skip_master_data = false

# minimal items to be inserted in one bulk
bulk_size = 128

# force flush the pending requests if we don't have enough items >= bulk_size
flush_bulk_time = "200ms"

# Ignore table without primary key
skip_no_pk_table = false

# MySQL data source
[[source]]
schema = "test"
tables = ["test_river_0000"]



# todu Target Mysql
targert_mysql_addr = "127.0.0.1:3306"
target_mysql_user = "root"
target_mysql_pass = "yaoyichen52"
target_mysql_charset = "utf8"
